# Generated by Django 2.0.1 on 2018-06-22 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ladder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('is_public', models.BooleanField(default=True, verbose_name='公開設定')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
        ),
        migrations.CreateModel(
            name='LearningStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(verbose_name='学習状態')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latter', models.ForeignKey(on_delete='次のラダー', related_name='latter_ladder', to='ladder.Ladder')),
                ('prior', models.ForeignKey(on_delete='前のラダー', related_name='prior_ladder', to='ladder.Ladder')),
                ('user', models.ForeignKey(on_delete='ユーザー', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='タグ名')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='タイトル')),
                ('description', models.TextField(verbose_name='説明文')),
                ('url', models.URLField(verbose_name='URL')),
                ('index', models.PositiveIntegerField(verbose_name='番号')),
                ('ladder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladder.Ladder', verbose_name='ラダー')),
            ],
        ),
        migrations.AddField(
            model_name='learningstatus',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladder.Unit', verbose_name='ユニット'),
        ),
        migrations.AddField(
            model_name='learningstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AddField(
            model_name='ladder',
            name='tags',
            field=models.ManyToManyField(blank=True, to='ladder.Tags', verbose_name='タグ'),
        ),
    ]
