# Generated by Django 2.0.6 on 2018-06-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0002_auto_20180622_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.TextField(blank=True, verbose_name='profile'),
        ),
    ]
