# Generated by Django 2.0.6 on 2018-06-30 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0003_auto_20180624_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='latter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latter_ladder', to='ladder.Ladder'),
        ),
        migrations.AlterField(
            model_name='link',
            name='prior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prior_ladder', to='ladder.Ladder'),
        ),
    ]
