# Generated by Django 2.0.6 on 2018-06-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0003_auto_20180623_1645'),
        ('ladder', '0003_auto_20180624_0517'),
    ]

    operations = [
    ]
